export const LOADING = 'LOADING';
export const FETCH_DATA_FIRST_TIME = 'FETCH_DATA_FIRST_TIME';
export const FETCH_DATA_FIRST_TIME_FAILED = 'FETCH_DATA_FIRST_TIME_FAILED';
export const SET_PAGINATION_PAGE = 'SET_PAGINATION_PAGE';
export const SET_CATEGORY_DETAIL_PAGE = 'SET_CATEGORY_DETAIL_PAGE';
export const SET_SINGLE_MODEL_DETAIL = 'SET_SINGLE_MODEL_DETAIL';